<?xml version="1.0" encoding="UTF-8"?><testsuites errors="0" failures="2" skipped="1" tests="4" time="7.226e-5"><testsuite errors="0" failures="0" name="" skipped="1" tests="1" time="0.0"><testcase name="skipped"><skipped/></testcase></testsuite><testsuite errors="0" failures="1" name="subSuite" skipped="0" tests="2" time="4.366e-5"><testcase name="passes" time="1.565e-5"/><testcase name="fails" time="2.801e-5"><failure></failure></testcase></testsuite><testsuite errors="0" failures="1" name="withMessage" skipped="0" tests="1" time="2.86e-5"><testcase name="errors" time="2.86e-5"><failure message="failure message
CallStack (from HasCallStack):
  error, called at test/Test/Syd/JUnitSpec.hs:32:20 in main:Test.Syd.JUnitSpec"></failure></testcase></testsuite></testsuites>