<?xml version="1.0" encoding="UTF-8"?><testsuites errors="0" failures="2" skipped="1" tests="4" time="0.0"><testsuite errors="0" failures="0" name="" skipped="1" tests="1" time="0.0"><testcase name="skipped"><skipped/></testcase></testsuite><testsuite errors="0" failures="1" name="subSuite" skipped="0" tests="2" time="0.0"><testcase name="passes" time="0.0"/><testcase name="fails" time="0.0"><failure></failure></testcase></testsuite><testsuite errors="0" failures="1" name="withMessage" skipped="0" tests="1" time="0.0"><testcase name="errors" time="0.0"><failure message="failure message
CallStack (from HasCallStack):
  error, called at test/Test/Syd/JUnitSpec.hs:37:18 in main:Test.Syd.JUnitSpec"></failure></testcase></testsuite></testsuites>